In [10]:
import numpy as np

N = 4
#A = np.zeros([3,3]) 
A = np.zeros([N+1,N+1]) 
#print (A)


for i in range(N+1):
    for j in range(N+1):
        if i == j:
            A[i,j] = -2
        if i == j + 1:
            A[i,j] = 1
        if i == j - 1:
            A[i,j] = 1
        


print (A)
























[[-2.  1.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.]
 [ 0.  1. -2.  1.  0.]
 [ 0.  0.  1. -2.  1.]
 [ 0.  0.  0.  1. -2.]]
