In [8]:
name = input("What is your name? ")# Read data from user
print ("Hello, %s." % name)
#=====
name = 'World'#define data here 
print ("Hello, %s." % name)
#use number sign for single-line comment
"""
multi-line comments
"""
print ("Good night, %s." % name)

What is your name? ChihhungChen
Hello, ChihhungChen.
Hello, World.
Good night, World.


In [17]:
import datetime as dt # import datetime module, call it "dt"
now = dt.datetime.now() #submodule
print (now)
print ("Current date and time:")
print ("Current year: %d" % now.year)
print ("Current month: %d" % now.month)
print ("Current day: %d" % now.day)
print ("Current hour: %d" % now.hour)
print ("Current minute: %d" % now.minute)
print ("Current second: %d" % now.second)
print ("Current date and time using strftime:")
print (now.strftime("%Y-%m-%d %H:%M:%S")) #define string format, Year-Month-Date Hour-Minute-Second
print ("okay")



2022-09-15 14:43:13.563506
Current date and time:
Current year: 2022
Current month: 9
Current day: 15
Current hour: 14
Current minute: 43
Current second: 13
Current date and time using strftime:
2022-09-15 14:43:13
okay


In [24]:
a = "10"
print (type(a))

print (a + a)

#====
a = float(a) # converting string to float
print(type(a)) #str(a), int(a),...
print (a + a)



<class 'str'>
1010
<class 'float'>
20.0


In [9]:

a = 2
b = 3
c = a + b 
print ("a + b = ", c)
print ("a + b = %d"%(c))

#=====
d = a * b
print ("a * b = ", d)
print ("a * b = %d"%(d))

#=====
e = a / b # 2/3=0.6666
print ("a / b =", e)


a + b =  5
a + b = 5


In [14]:
print ("3^2 = %.2f"%(3.*3.))
print ("3^2 = %.2f"%(3.** 2.))
print ("3^2 = %.2f"%(pow(3.,2.)))

3^2 = 9.00
3^2 = 9.00
3^2 = 9.00


In [20]:
a = 60            # 60 = 0011 1100 
b = 13            # 13 = 0000 1101 
c = 0

c = a & b;        # 12 = 0000 1100
print (" a & b = ", c)

c = a | b;        # 61 = 0011 1101 
print ("a | b = ", c)

c = a ^ b;        # 49 = 0011 0001
print ("a ^ b = ", c)

c = ~a;           # -61 = 1100 0011
print ("~a  = ", c)

c = a << 2;       # 240 = 1111 0000
print ("a << 2 = ", c)

c = a >> 2;       # 15 = 0000 1111
print ("a >> 2 = ", c)

 a & b =  12
a | b =  61
a ^ b =  49
~a  =  -61
a << 2 =  240
a >> 2 =  15


In [28]:

import numpy as np
#---------- Method 1 ----------
mass = 2. #kg
velocity = -10.5 #m/s
KE = 0.5 * mass * velocity**2.
print ("Kinectic energy is %.3f J"%(KE))


Kinectic energy is 110.250 J


In [33]:
#define function 
def ComputeKE(m,v):
    KE = 0.5 * m * v**2
    return KE

#====
mass = 2. #kg
velocity = -10.5 #m/s 
KE = ComputeKE(mass, velocity)
print ("Kinectic energy is %.3f J"%(KE))



Kinectic energy is 110.250 J


In [36]:

#====
mass = 2. #kg
velocity = -10.5 #m/s 
KE = ComputeKE(mass, velocity)
print ("Kinectic energy is %.3f J"%(KE))
#====
mass = 1. #kg
velocity = 2.5 #m/s 
KE = ComputeKE(mass, velocity)
print ("Kinectic energy is %.3f J"%(KE))

#====
mass = 1. #kg
velocity = 0.3 #m/s 
KE = ComputeKE(mass, velocity)
print ("Kinectic energy is %.3f J"%(KE))

Kinectic energy is 110.250 J
Kinectic energy is 3.125 J
Kinectic energy is 0.045 J


In [41]:
mass = np.array([2.0,1.0, 1.0 ]) # in units of kg
velocity = np.array([-10.5,2.5, 0.3 ]) # in units of m/s
print (mass)
print (velocity)
KE = ComputeKE(mass, velocity)
print (KE)

[2. 1. 1.]
[-10.5   2.5   0.3]
[1.1025e+02 3.1250e+00 4.5000e-02]


In [ ]:
#----------Function + Numpy Array----------
mass = np.array([1.1,2.1,3.1])
velocity = np.array([0.5,4.3,5.1])
KE = ComputeKE(mass, velocity)
print ("KE are %.3f J,%.3f J, %.3f J "%(KE[0],KE[1],KE[2]))