In [16]:
import numpy as np

N = 4
T_low = 0 # degrees
T_high = 50 # degrees

#A = np.zeros([3,3]) 
A = np.zeros([N+1,N+1]) 
b = np.zeros(N+1)
#print (A)


for i in range(N+1):
    for j in range(N+1):
        if i == j:
            A[i,j] = -2
        if i == j + 1:
            A[i,j] = 1
        if i == j - 1:
            A[i,j] = 1
#BC for A
A[0,0] = 1
A[N,N] = 1
A[0,1] = 0
A[N,N-1] = 0
#BC for b
b[0] = T_low
b[N] = T_high
print (A)
print (b)







[[ 1.  0.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.]
 [ 0.  1. -2.  1.  0.]
 [ 0.  0.  1. -2.  1.]
 [ 0.  0.  0.  0.  1.]]
[ 0.  0.  0.  0. 50.]


In [ ]:
N = 10
A = np.zeros([N+1,N+1]) 

#=====
for i in range(1, N):
    for j in range(1, N):
        if j == i:# Set the diagonals to -2
            A[i, j] = -2.
        elif j == i+1: # non-zero off-diagonals, upper part
            A[i,j] = 1.
        elif j == i-1: # non-zero off-diagonals, lower part
            A[i,j] = 1.


#===== Boundary Conditions =====            
# Boundary Conditions for A
A[0,0]  = 1.
A[1,0] = 1.
A[N-1,N] = 1.
A[N,N] = 1.
# Boundary Conditions for b
b[0]  = T_low
b[N] = T_high

print (A)   
print (b)

#=====
T_arr = np.linalg.solve(A,b)
h = float(Lx)/N # step size for Finite Difference
x_arr = h * (np.arange(N+1))
#print (x_arr)
fig = plt.figure( dpi = 70 ) # dots per inch
fig.set_size_inches(6,4)
plt.plot(x_arr, T_arr,'--ko',label = 'Numerical Solution')
plt.xlabel(r'$x\; \rm (m)$')
plt.ylabel(r'$T\; \rm ( ^\circ C)$')
#plt.legend(loc="upper left")
plt.tight_layout()
plt.savefig("Unit_4.14b_1d_beta_0.png")